"""primera version!!

Revision ID: 7872df842655
Revises: 
Create Date: 2018-04-20 02:01:01.161937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7872df842655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_cancion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Unicode(length=255), nullable=False),
    sa.Column('artista', sa.Unicode(length=255), nullable=True),
    sa.Column('album', sa.Unicode(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=False),
    sa.Column('texto', sa.Text(convert_unicode=True), nullable=True),
    sa.Column('spotify_uri', sa.Unicode(length=50), nullable=True),
    sa.Column('youtube_url', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_cancion')
    # ### end Alembic commands ###
